[package]
name = "health_haven_medical_centre"
version = "0.1.0"
edition = "2021"
description = "A medical centre application built using Actix-web, providing health services and information."
authors = ["Your Name <faroukpandor@gmail.com>"]
license = "MIT"
rust-version = "1.60.0"
categories = ["web-programming", "health", "actix"]
keywords = ["actix", "web", "medical", "healthcare"]

[dependencies]
actix-web = "4.0"   # Web framework for building web applications
serde = { version = "1.0", features = ["derive"] }  # For serialization
serde_json = "1.0"  # For JSON handling
sqlx = { version = "0.5", features = ["macros", "runtime-actix-native-tls"] }  # Enable Actix runtime with native TLS
syn = { version = "1.0", features = ["derive", "parsing"] }  # For parsing and code generation

# Optional additional dependencies
dotenv = "0.15"  # For loading environment variables from a .env file
log = "0.4"  # For logging support
tokio = { version = "1.0", features = ["full"] }  # If you need async features

# Testing dependencies (uncomment if needed)
# actix-rt = "2.5"  # Actix runtime for async testing
# tokio-test = "0.4"  # Testing utilities for Tokio
# reqwest = { version = "0.11", features = ["json"] }  # HTTP client for making requests in tests
